-- btree-gist 확장 설치 필요
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- public."IDENTITY_TB" definition

-- Drop table

-- DROP TABLE public."IDENTITY_TB";

CREATE TABLE public."IDENTITY_TB" (
                                      identity_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      email varchar(255) NOT NULL,
                                      "password" varchar(255) NULL,
                                      "role" varchar(255) NOT NULL,
                                      unsubscribe bool NOT NULL,
                                      created_at timestamptz NOT NULL,
                                      updated_at timestamptz NOT NULL,
                                      CONSTRAINT "IDENTITY_TB_pkey" PRIMARY KEY (identity_id),
                                      CONSTRAINT "IDENTITY_TB_role_check" CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'TRAINER'::character varying, 'GUEST'::character varying, 'SYSTEM'::character varying])::text[]))),
	CONSTRAINT "UK3d7i74jv6iki7l25x0nlj7q1e" UNIQUE (email)
);

-- public."OAUTH_TB" definition

-- Drop table

-- DROP TABLE public."OAUTH_TB";

CREATE TABLE public."OAUTH_TB" (
                                   oauth_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   "oauth_provider" varchar(255) NOT NULL,
                                   created_at timestamptz NOT NULL,
                                   updated_at timestamptz NOT NULL,
                                   oauth_user_id varchar(255) NOT NULL,
                                   identity_id int8 NOT NULL,
                                   CONSTRAINT "OAUTH_TB_pkey" PRIMARY KEY (oauth_id),
                                   CONSTRAINT oauth_provider_user_id UNIQUE (oauth_provider, oauth_user_id)
);


-- public."OAUTH_TB" foreign keys

ALTER TABLE public."OAUTH_TB" ADD CONSTRAINT "FK16m5bad43uosx83c6gcvqr0ke" FOREIGN KEY (identity_id) REFERENCES public."IDENTITY_TB"(identity_id);

-- public."USER_TB" definition

-- Drop table

-- DROP TABLE public."USER_TB";

CREATE TABLE public."USER_TB" (
                                  user_id int8 NOT NULL,
                                  first_name varchar(255) NULL,
                                  last_name varchar(255) NULL,
                                  phone_number varchar(255) NOT NULL,
                                  created_at timestamptz NOT NULL,
                                  updated_at timestamptz NOT NULL,
                                  sex varchar(255) NULL,
                                  CONSTRAINT "PK_USER_TB" PRIMARY KEY (user_id),
                                  CONSTRAINT phone_number UNIQUE (phone_number)
);

-- public."USER_SESSION_TB" definition

-- Drop table

-- DROP TABLE public."USER_SESSION_TB";

CREATE TABLE public."USER_SESSION_TB" (
                                          session_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                          user_id int8 NOT NULL,
                                          total_sessions int4 NOT NULL,
                                          used_sessions int4 DEFAULT 0 NOT NULL,
                                          expire_at timestamptz NULL,
                                          status varchar(255) NOT NULL,
                                          created_at timestamptz NOT NULL,
                                          updated_at timestamptz NOT NULL,
                                          session_type varchar(255) NOT NULL,
                                          "version" int8 NOT NULL,
                                          start_at timestamptz(6) NULL,
                                          CONSTRAINT "USER_SESSION_TB_pkey" PRIMARY KEY (session_id)
);


-- public."USER_SESSION_TB" foreign keys

ALTER TABLE public."USER_SESSION_TB" ADD CONSTRAINT "FK_USER_TO_SESSION" FOREIGN KEY (user_id) REFERENCES public."USER_TB"(user_id);



-- public."USER_SESSION_HISTORY_TB" definition

-- Drop table

-- DROP TABLE public."USER_SESSION_HISTORY_TB";

CREATE TABLE public."USER_SESSION_HISTORY_TB" (
                                                  history_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                  user_session_id int8 NOT NULL,
                                                  user_id int8 NOT NULL,
                                                  change_type varchar(255) NOT NULL,
                                                  amount int4 NOT NULL,
                                                  remaining_sessions int4 NOT NULL,
                                                  description varchar(255) NULL,
                                                  created_at timestamptz NOT NULL,
                                                  updated_at timestamptz NOT NULL,
                                                  session_type varchar(255) NULL,
                                                  modifier_id int8 NOT NULL,
                                                  modifier_role varchar(255) NOT NULL,
                                                  modifier_name varchar(255) NULL,
                                                  expired_at_snapshot timestamptz NOT NULL,
                                                  CONSTRAINT "PK_USER_SESSION_HISTORY_TB" PRIMARY KEY (history_id)
);
CREATE INDEX "IDX_SESSION_HISTORY_USER_DATE" ON public."USER_SESSION_HISTORY_TB" USING btree (user_id, created_at DESC);


-- public."USER_SESSION_HISTORY_TB" foreign keys

ALTER TABLE public."USER_SESSION_HISTORY_TB" ADD CONSTRAINT "FK_SESSION_TO_HISTORY" FOREIGN KEY (user_session_id) REFERENCES public."USER_SESSION_TB"(session_id);


-- public."USER_MEMBERSHIP_TB" definition

-- Drop table

-- DROP TABLE public."USER_MEMBERSHIP_TB";

CREATE TABLE public."USER_MEMBERSHIP_TB" (
                                             membership_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             user_id int8 NOT NULL,
                                             plan_type varchar(255) NOT NULL,
                                             status varchar(255) NOT NULL,
                                             started_at timestamptz NOT NULL,
                                             expired_at timestamptz NOT NULL,
                                             created_at timestamptz NOT NULL,
                                             updated_at timestamptz NOT NULL,
                                             suspend_end_at timestamptz(6) NULL,
                                             suspend_start_at timestamptz(6) NULL,
                                             "version" int8 NOT NULL,
                                             CONSTRAINT "USER_MEMBERSHIP_TB_pkey" PRIMARY KEY (membership_id)
);


-- public."USER_MEMBERSHIP_TB" foreign keys

ALTER TABLE public."USER_MEMBERSHIP_TB" ADD CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES public."USER_TB"(user_id) ON DELETE CASCADE;

-- public."USER_MEMBERSHIP_HISTORY_TB" definition

-- Drop table

-- DROP TABLE public."USER_MEMBERSHIP_HISTORY_TB";

CREATE TABLE public."USER_MEMBERSHIP_HISTORY_TB" (
                                                     membership_history_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                     created_at timestamptz(6) NOT NULL,
                                                     updated_at timestamptz(6) NOT NULL,
                                                     after_expired_at_snapshot timestamptz(6) NOT NULL,
                                                     amount_days int4 NOT NULL,
                                                     before_expired_at_snapshot timestamptz(6) NULL,
                                                     change_type varchar(255) NOT NULL,
                                                     description varchar(255) NOT NULL,
                                                     membership_id int8 NOT NULL,
                                                     plan_type varchar(255) NOT NULL,
                                                     modifier_id int8 NOT NULL,
                                                     modifier_name varchar(255) NULL,
                                                     modifier_role varchar(255) NOT NULL,
                                                     started_at_snapshot timestamptz(6) NOT NULL,
                                                     status varchar(255) NULL,
                                                     user_id int8 NOT NULL,
                                                     CONSTRAINT "USER_MEMBERSHIP_HISTORY_TB_change_type_check" CHECK (((change_type)::text = ANY ((ARRAY['PURCHASE'::character varying, 'EXTEND'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying, 'SUSPEND'::character varying, 'RESUME'::character varying, 'ROLLBACK'::character varying])::text[]))),
	CONSTRAINT "USER_MEMBERSHIP_HISTORY_TB_pkey" PRIMARY KEY (membership_history_id),
	CONSTRAINT "USER_MEMBERSHIP_HISTORY_TB_plan_type_check" CHECK (((plan_type)::text = ANY ((ARRAY['MONTH_1'::character varying, 'MONTH_3'::character varying, 'MONTH_6'::character varying, 'MONTH_12'::character varying])::text[]))),
	CONSTRAINT "USER_MEMBERSHIP_HISTORY_TB_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying])::text[])))
);

-- public."CLASS_TEMPLATE_TB" definition

-- Drop table

-- DROP TABLE public."CLASS_TEMPLATE_TB";

CREATE TABLE public."CLASS_TEMPLATE_TB" (
                                            template_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            title varchar(255) NOT NULL,
                                            description varchar(255) NULL,
                                            capacity int4 NOT NULL,
                                            duration_minutes int4 NOT NULL,
                                            "recommend_level" varchar(255) NULL,
                                            created_at timestamptz NOT NULL,
                                            updated_at timestamptz NOT NULL,
                                            deleted_at timestamptz NULL,
                                            "class_kind" varchar(255) NOT NULL,
                                            CONSTRAINT "PK_CLASS_TEMPLATE_TB" PRIMARY KEY (template_id)
);

-- public."CLASS_RECURRENCE_GROUP_TB" definition

-- Drop table

-- DROP TABLE public."CLASS_RECURRENCE_GROUP_TB";

CREATE TABLE public."CLASS_RECURRENCE_GROUP_TB" (
                                                    group_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                    trainer_id int8 NOT NULL,
                                                    class_template_id int8 NOT NULL,
                                                    start_date date NOT NULL,
                                                    end_date date NOT NULL,
                                                    start_time time NOT NULL,
                                                    repeat_days jsonb NULL,
                                                    time_zone_id varchar(255) NOT NULL,
                                                    recurrence_type varchar(255) NOT NULL,
                                                    created_at timestamptz NOT NULL,
                                                    updated_at timestamptz NOT NULL,
                                                    remaining_capacity int4 DEFAULT 0 NOT NULL,
                                                    status varchar(255) NULL,
                                                    CONSTRAINT "PK_CLASS_RECURRENCE_GROUP_TB" PRIMARY KEY (group_id),
                                                    CONSTRAINT ck_recurrence_date_order CHECK ((start_date <= end_date))
);


-- public."CLASS_RECURRENCE_GROUP_TB" foreign keys

ALTER TABLE public."CLASS_RECURRENCE_GROUP_TB" ADD CONSTRAINT "FK_CLASS_TEMPLATE_TB_TO_CLASS_RECURRENCE_GROUP_TB" FOREIGN KEY (class_template_id) REFERENCES public."CLASS_TEMPLATE_TB"(template_id);
ALTER TABLE public."CLASS_RECURRENCE_GROUP_TB" ADD CONSTRAINT "FK_USER_TB_TO_CLASS_RECURRENCE_GROUP_TB" FOREIGN KEY (trainer_id) REFERENCES public."USER_TB"(user_id);

-- public."CLASS_SCHEDULE_TB" definition

-- Drop table

-- DROP TABLE public."CLASS_SCHEDULE_TB";

CREATE TABLE public."CLASS_SCHEDULE_TB" (
                                            class_schedule_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            trainer_id int8 NOT NULL,
                                            class_template_id int8 NULL,
                                            time_range tstzrange NOT NULL,
                                            recurrence_group_id int8 NULL,
                                            status varchar(255) NULL,
                                            capacity int4 DEFAULT 0 NOT NULL,
                                            created_at timestamptz NOT NULL,
                                            updated_at timestamptz NOT NULL,
                                            CONSTRAINT "PK_CLASS_SCHEDULE_TB" PRIMARY KEY (class_schedule_id),
                                            CONSTRAINT ck_schedule_time_order CHECK ((upper(time_range) > lower(time_range))),
                                            CONSTRAINT no_schedule_overlap EXCLUDE USING gist (trainer_id WITH =, time_range WITH &&) WHERE (((status)::text <> ALL (ARRAY['CANCELED'::text, 'CANCELLED'::text])))
);
CREATE INDEX no_schedule_overlap ON public."CLASS_SCHEDULE_TB" USING gist (trainer_id, time_range) WHERE ((status)::text <> ALL (ARRAY['CANCELED'::text, 'CANCELLED'::text]));


-- public."CLASS_SCHEDULE_TB" foreign keys

ALTER TABLE public."CLASS_SCHEDULE_TB" ADD CONSTRAINT "FK_CLASS_TEMPLATE_TB_TO_CLASS_SCHEDULE_TB_1" FOREIGN KEY (class_template_id) REFERENCES public."CLASS_TEMPLATE_TB"(template_id);
ALTER TABLE public."CLASS_SCHEDULE_TB" ADD CONSTRAINT "FK_GROUP_TO_SCHEDULE" FOREIGN KEY (recurrence_group_id) REFERENCES public."CLASS_RECURRENCE_GROUP_TB"(group_id);
ALTER TABLE public."CLASS_SCHEDULE_TB" ADD CONSTRAINT "FK_USER_TB_TO_CLASS_SCHEDULE_TB_1" FOREIGN KEY (trainer_id) REFERENCES public."USER_TB"(user_id);


-- public."BOOKING_TB" definition

-- Drop table

-- DROP TABLE public."BOOKING_TB";

CREATE TABLE public."BOOKING_TB" (
                                     booking_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     class_schedule_id int8 NOT NULL,
                                     user_id int8 NOT NULL,
                                     status varchar(255) NOT NULL,
                                     created_at timestamptz NOT NULL,
                                     updated_at timestamptz NOT NULL,
                                     user_session_id int8 NULL,
                                     "version" int8 DEFAULT 0 NOT NULL,
                                     booking_type varchar(255) NOT NULL,
                                     CONSTRAINT "PK_BOOKING_TB" PRIMARY KEY (booking_id)
);
CREATE UNIQUE INDEX idx_booking_user_active ON public."BOOKING_TB" USING btree (user_id, class_schedule_id) WHERE ((status)::text <> 'CANCELLED'::text);


-- public."BOOKING_TB" foreign keys

ALTER TABLE public."BOOKING_TB" ADD CONSTRAINT "FK_SCHEDULE_TO_BOOKING" FOREIGN KEY (class_schedule_id) REFERENCES public."CLASS_SCHEDULE_TB"(class_schedule_id);
ALTER TABLE public."BOOKING_TB" ADD CONSTRAINT "FK_SESSION_TO_BOOKING" FOREIGN KEY (user_session_id) REFERENCES public."USER_SESSION_TB"(session_id) ON DELETE SET NULL;
ALTER TABLE public."BOOKING_TB" ADD CONSTRAINT "FK_USER_TO_BOOKING" FOREIGN KEY (user_id) REFERENCES public."USER_TB"(user_id);

-- public."BOOKING_HISTORY_TB" definition

-- Drop table

-- DROP TABLE public."BOOKING_HISTORY_TB";

CREATE TABLE public."BOOKING_HISTORY_TB" (
                                             history_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             booking_id int8 NOT NULL,
                                             modifier_id int8 NOT NULL,
                                             modifier_role varchar(255) NOT NULL,
                                             action_type varchar(255) NOT NULL,
                                             previous_status varchar(255) NULL,
                                             new_status varchar(255) NOT NULL,
                                             reason varchar(255) NULL,
                                             created_at timestamptz NOT NULL,
                                             updated_at timestamptz NOT NULL,
                                             booking_type varchar(255) NULL,
                                             cancellation_type varchar(255) NULL,
                                             CONSTRAINT "BOOKING_HISTORY_TB_cancellation_type_check" CHECK (((cancellation_type)::text = ANY ((ARRAY['FREE_CANCEL'::character varying, 'PENALTY_CANCEL'::character varying, 'IMPOSSIBLE'::character varying])::text[]))),
	CONSTRAINT "PK_BOOKING_HISTORY_TB" PRIMARY KEY (history_id)
);
CREATE INDEX "IDX_BOOKING_HISTORY_BOOKING_ID" ON public."BOOKING_HISTORY_TB" USING btree (booking_id, created_at DESC);

-- public."TRAINER_CALENDAR_R" definition

-- Drop table

-- DROP TABLE public."TRAINER_CALENDAR_R";

CREATE TABLE public."TRAINER_CALENDAR_R" (
                                             calendar_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             trainer_id int8 NOT NULL,
                                             source_type varchar(255) NOT NULL,
                                             source_id int8 NOT NULL,
                                             time_range tstzrange NOT NULL,
                                             status varchar(255) NULL,
                                             created_at timestamptz NOT NULL,
                                             updated_at timestamptz NULL,
                                             trainer_name varchar(255) NOT NULL,
                                             title varchar(255) NOT NULL,
                                             CONSTRAINT "PK_TRAINER_CALENDAR_R" PRIMARY KEY (calendar_id)
);
CREATE INDEX ix_cal_trainer_range ON public."TRAINER_CALENDAR_R" USING gist (trainer_id, time_range);
CREATE UNIQUE INDEX ux_cal_source ON public."TRAINER_CALENDAR_R" USING btree (source_type, source_id);

-- public."TRAINER_TIME_OFF_TB" definition

-- Drop table

-- DROP TABLE public."TRAINER_TIME_OFF_TB";

CREATE TABLE public."TRAINER_TIME_OFF_TB" (
                                              trainer_block_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                              user_id int8 NOT NULL,
                                              time_range tstzrange NOT NULL,
                                              created_at timestamptz NOT NULL,
                                              updated_at timestamptz NOT NULL,
                                              "type" varchar(255) NOT NULL,
                                              status varchar(255) NOT NULL,
                                              reason varchar(255) NULL,
                                              CONSTRAINT "PK_TRAINER_BLOCK_TB" PRIMARY KEY (trainer_block_id)
);


-- public."TRAINER_TIME_OFF_TB" foreign keys

ALTER TABLE public."TRAINER_TIME_OFF_TB" ADD CONSTRAINT "FK_USER_TB_TO_TRAINER_BLOCK_TB_1" FOREIGN KEY (user_id) REFERENCES public."USER_TB"(user_id);


-- public."PRODUCT_TB" definition

-- Drop table

-- DROP TABLE public."PRODUCT_TB";

CREATE TABLE public."PRODUCT_TB" (
                                     product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     "name" varchar(255) NOT NULL,
                                     "type" varchar(255) NOT NULL,
                                     price int8 NOT NULL,
                                     code varchar(255) NOT NULL,
                                     created_at timestamptz NOT NULL,
                                     updated_at timestamptz NOT NULL,
                                     product_status varchar(255) NOT NULL,
                                     CONSTRAINT "PRODUCT_TB_pkey" PRIMARY KEY (product_id),
                                     CONSTRAINT "PRODUCT_TB_product_status_check" CHECK (((product_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

-- public."PAYMENT_RECORD_TB" definition

-- Drop table

-- DROP TABLE public."PAYMENT_RECORD_TB";

CREATE TABLE public."PAYMENT_RECORD_TB" (
                                            payment_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            user_id int8 NOT NULL,
                                            status varchar(255) NOT NULL,
                                            provider_payment_id varchar(255) NULL,
                                            amount_cents int8 NOT NULL,
                                            created_at timestamptz NOT NULL,
                                            updated_at timestamptz NOT NULL,
                                            snapshot_product_name varchar(255) NOT NULL,
                                            snapshot_product_type varchar(255) NOT NULL,
                                            snapshot_plan_name varchar(255) NOT NULL,
                                            checkout_url text NULL,
                                            contract_snapshot text NOT NULL,
                                            source_id int8 NULL,
                                            refund_actor_id int8 NULL,
                                            refund_actor_role varchar(255) NULL,
                                            CONSTRAINT "PK_PAYMENT_RECORD_TB" PRIMARY KEY (payment_id),
                                            CONSTRAINT provider_payment_id UNIQUE (provider_payment_id)
);
CREATE INDEX idx_payment_pending_check ON public."PAYMENT_RECORD_TB" USING btree (user_id, snapshot_plan_name, status, created_at DESC);
CREATE UNIQUE INDEX ux_payment_provider ON public."PAYMENT_RECORD_TB" USING btree (provider_payment_id);


-- public."PAYMENT_RECORD_TB" foreign keys

ALTER TABLE public."PAYMENT_RECORD_TB" ADD CONSTRAINT "FK_USER_TO_PAYMENT" FOREIGN KEY (user_id) REFERENCES public."USER_TB"(user_id);


